In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [3]:
df=pd.read_csv('creditcard.csv')

In [4]:
df.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [5]:
df.shape

(284807, 31)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [1]:
df['Class'].value_counts()

NameError: name 'df' is not defined

In [6]:
from imblearn.combine import SMOTEENN

In [12]:
x=df.drop(columns=['Class'],axis=1)
y=df['Class']

In [ ]:
x_resampled,y_resampled=sm.fit_resample(x,y)

In [14]:
sm=SMOTEENN()

In [ ]:
xr_train,xr_test,yr_train,yr_test=train_test_split(x_resampled,y_resampled,test_size=0.2)

In [7]:
legit=df[df['Class']==0]
fraud=df[df['Class']==1]

In [8]:
legit['Amount'].describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [9]:
fraud['Amount'].describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [10]:
legit_sample=legit.sample(n=492)

In [41]:
new_df=pd.concat([legit_sample,fraud],axis=0)

In [20]:
 new_df=new_df.sample(frac=1).reset_index(drop=True)

In [42]:
new_df.tail()

Time        V1        V2        V3        V4        V5        V6  \
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[5 rows x 31 columns]

In [43]:
X=new_df.drop(columns=['Class'],axis=1)
Y=new_df['Class']

In [27]:
x

Time         V1        V2         V3        V4         V5        V6  \
0    170375.0  -0.668726  0.267670  -0.566598 -0.274168   0.334368 -1.028663   
1     41273.0 -11.682215  6.332882 -13.297109  7.690772 -10.889891 -2.792360   
2      8169.0   0.857321  4.093912  -7.423894  7.380245   0.973366 -2.730762   
3    110087.0   1.934946  0.650678  -0.286957  3.987828   0.316052 -0.099449   
4    170348.0   1.991976  0.158476  -2.583441  0.408670   1.151147 -0.096695   
..        ...        ...       ...        ...       ...        ...       ...   
979   61992.0  -1.526152  0.105099   1.898958  0.165714  -1.204741  0.306244   
980  121124.0  -0.295631  1.659411   0.331328  4.384554   0.431815  0.744604   
981  149676.0   1.833191  0.745333  -1.133009  3.893556   0.858164  0.910235   
982   51544.0  -0.283661  0.717007  -0.029250 -0.359441   2.652987  3.725111   
983   71723.0  -0.801208  1.141701   1.035197 -0.332023   0.496948  0.025694   

            V7        V8        V9  ...       V20       V21       V22  \
0     2.132333 -0.825006  0.094350  ... -0.449412  0.102476  1.038655   
1   -12.561783  7.287122 -7.570322  ... -1.009320  2.133456 -1.271509   
2    -1.496497  0.543015 -2.351190  ...  0.483303  0.375026  0.145400   
3    -0.021483 -0.172327  0.508730  ... -0.344452 -0.173602 -0.190974   
4     0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135   
..         ...       ...       ...  ...       ...       ...       ...   
979  -0.515797  0.293523 -0.249061  ...  0.001827 -0.159007  0.591396   
980   0.117399  0.624921 -1.776615  ...  0.101211  0.385946  1.152448   
981  -0.498200  0.344703 -0.667939  ... -0.085579  0.039289  0.181652   
982   0.206798  0.932261 -0.418040  ...  0.004838 -0.108348 -0.291255   
983   0.600959  0.090206 -0.091190  ...  0.177725 -0.279846 -0.640845   

          V23       V24       V25       V26       V27       V28  Amount  
0    0.225278  0.005507  0.123622 -0.196650 -0.072343 -0.323807  212.58  
1   -0.035304  0.615054  0.349024 -0.428923 -0.694935 -0.818970  173.07  
2    0.240603 -0.234649 -1.004881  0.435832  0.618324  0.148469    1.00  
3    0.219976 -0.216597 -0.136692 -0.129954 -0.050077 -0.051082    1.00  
4   -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53  
..        ...       ...       ...       ...       ...       ...     ...  
979  0.052769  0.052640 -0.443428 -0.183372  0.795368  0.689490  100.00  
980 -0.136170  0.599569 -0.514307  0.600934  0.341999  0.206464   10.59  
981  0.072981 -0.155299 -0.149891  0.012792  0.040854  0.022903   17.39  
982 -0.293121  1.004151  0.425776 -0.367583  0.079486  0.051896    1.00  
983 -0.013863 -0.788252 -0.094168  0.148268  0.270308  0.155753    5.49  

[984 rows x 30 columns]

In [44]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [32]:
x_train.shape

(787, 30)

In [33]:
y_train.shape

(787,)

In [45]:
model=LogisticRegression()

In [46]:
model.fit(x_train,y_train)

LogisticRegression()

In [47]:
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)

In [48]:
print(training_data_accuracy)

0.9174078780177891


In [50]:
x_test_prediction=model.predict(x_test)
testing_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [51]:
print(testing_data_accuracy)

0.8730964467005076


In [53]:
print(confusion_matrix(y_test,x_test_prediction))
print(precision_score(y_test,x_test_prediction))

[[89 10]
 [15 83]]
0.8924731182795699


In [55]:
print(recall_score(y_test,x_test_prediction))

0.8469387755102041


In [56]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)

In [58]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [59]:
x_test_prediction=clf.predict(x_test)
testing_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [60]:
print(testing_data_accuracy)

0.9289340101522843


In [61]:
print(confusion_matrix(y_test,x_test_prediction))
print(precision_score(y_test,x_test_prediction))

[[98  1]
 [13 85]]
0.9883720930232558


In [62]:
print(recall_score(y_test,x_test_prediction))

0.8673469387755102


In [63]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [64]:
gnb = GaussianNB()
mnb = MultinomialNB()
bnb = BernoulliNB()

In [65]:
gnb.fit(x_train,y_train)
y_pred1 = gnb.predict(x_test)
print(accuracy_score(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))
print(recall_score(y_test,y_pred1))


0.8730964467005076
[[98  1]
 [24 74]]
0.7551020408163265


In [67]:
bnb.fit(x_train,y_train)
y_pred3 = bnb.predict(x_test)
print(accuracy_score(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))
print(recall_score(y_test,y_pred3))

0.8883248730964467
[[96  3]
 [19 79]]
0.8061224489795918


In [68]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

In [79]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=100, random_state=2)
abc = AdaBoostClassifier(n_estimators=100, random_state=2)
bc = BaggingClassifier(n_estimators=100, random_state=2)
etc = ExtraTreesClassifier(n_estimators=100, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=100,random_state=2)
xgb = XGBClassifier(n_estimators=100,random_state=2)

In [80]:
clfs = {
    'SVC' : svc,
    'KN' : knc,  
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    'BgC': bc, 
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

In [81]:
def train_classifier(clf,x_train,y_train,x_test,y_test):
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    recall = recall_score(y_test,y_pred)
    
    return accuracy,precision,recall

In [82]:
accuracy_scores = []
precision_scores = []
recall_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision,current_recall = train_classifier(clf, x_train,y_train,x_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print('\n')
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)

For  SVC
Accuracy -  0.49746192893401014
Precision -  0.49746192893401014
Recall -  1.0


For  KN
Accuracy -  0.700507614213198
Precision -  0.7052631578947368
Recall -  0.6836734693877551


For  DT
Accuracy -  0.9289340101522843
Precision -  0.9883720930232558
Recall -  0.8673469387755102


For  LR
Accuracy -  0.9289340101522843
Precision -  0.9666666666666667
Recall -  0.8877551020408163


For  RF
Accuracy -  0.934010152284264
Precision -  1.0
Recall -  0.8673469387755102


For  AdaBoost
Accuracy -  0.9137055837563451
Precision -  0.9550561797752809
Recall -  0.8673469387755102


For  BgC
Accuracy -  0.9137055837563451
Precision -  0.945054945054945
Recall -  0.8775510204081632


For  ETC
Accuracy -  0.9187817258883249
Precision -  0.9880952380952381
Recall -  0.8469387755102041


For  GBDT
Accuracy -  0.9137055837563451
Precision -  0.9655172413793104
Recall -  0.8571428571428571


For  xgb
Accuracy -  0.9187817258883249
Precision -  0.9555555555555556
Recall -  0.8775510204081632



In [83]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores,'Recall':recall_scores}).sort_values('Recall',ascending=False)


In [78]:
performance_df

Algorithm  Accuracy  Precision    Recall
0       SVC  0.497462   0.497462  1.000000
2        DT  0.939086   0.988636  0.887755
3        LR  0.928934   0.966667  0.887755
6       BgC  0.928934   0.966667  0.887755
4        RF  0.939086   1.000000  0.877551
5  AdaBoost  0.918782   0.955556  0.877551
8      GBDT  0.918782   0.955556  0.877551
9       xgb  0.913706   0.955056  0.867347
7       ETC  0.923858   0.988235  0.857143
1        KN  0.700508   0.705263  0.683673

In [90]:
n_estimators=[int(x) for x in np.linspace(start=100,stop=1200,num=12)]
max_features=['auto','sqrt']
max_depth=[int(x) for x in np.linspace(5,30,num=6)]
min_samples_split=[2,5,10,15,100]
min_samples_leaf=[1,2,5,10]
from sklearn.model_selection import RandomizedSearchCV
random_grid={
    'n_estimators':n_estimators,
    'max_features':max_features,
    'max_depth':max_depth,
    'min_samples_split':min_samples_split,
    'min_samples_leaf':min_samples_leaf
}
rf=GradientBoostingClassifier()
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,scoring='neg_mean_squared_error',n_iter=10,cv=5,verbose=2,random_state=42,n_jobs=1)

In [91]:
rf_random.fit(x_train,y_train)
y_pred=rf_random.predict(x_test)
print('Accuracy score = ',accuracy_score(y_test,y_pred))
print('precision score = ',precision_score(y_test,y_pred))
print('Recall score = ',recall_score(y_test,y_pred))


Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10 


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10, total=   1.9s
[CV] n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10 


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.8s remaining:    0.0s


[CV]  n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10, total=   1.9s
[CV] n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10 
[CV]  n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10, total=   1.9s
[CV] n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10 
[CV]  n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10, total=   1.9s
[CV] n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10 
[CV]  n_estimators=900, min_samples_split=5, min_samples_leaf=5, max_features=sqrt, max_depth=10, total=   1.9s
[CV] n_estimators=1100, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=15 
[CV]  n_estimators=1100, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=15, total=   3.0s
[CV] n_estimators=1100, min_samples_split=10, mi

[CV]  n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5, total=   0.9s
[CV] n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5 
[CV]  n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5, total=   0.8s
[CV] n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5 
[CV]  n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5, total=   0.8s
[CV] n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5 
[CV]  n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5, total=   0.9s
[CV] n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5 
[CV]  n_estimators=700, min_samples_split=10, min_samples_leaf=2, max_features=sqrt, max_depth=5, total=   0.9s
[CV] n_estimators=700, min_samples_split=15, min_sam

[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:  3.0min finished


Accuracy score =  0.9187817258883249
precision score =  0.9767441860465116
Recall score =  0.8571428571428571
